### ISSUE TITLE
Windows installation error

### ISSUE THREAD

**Issue by robmarkcole** [simonw/datasette#187] opened 2018-03-27 16:04 UTC
On attempting install on a Win 7 PC with py 3.6.2 (Anaconda dist) I get the error:

```
Collecting uvloop>=0.5.3 (from Sanic==0.7.0->datasette)
  Downloading uvloop-0.9.1.tar.gz (1.8MB)
    100% |¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦| 1.8MB 12.8MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\RCole\AppData\Local\Temp\pip-build-juakfqt8\uvloop\setup.py
", line 10, in <module>
        raise RuntimeError('uvloop does not support Windows at the moment')
    RuntimeError: uvloop does not support Windows at the moment
```

**Comment by progpow** [comment] 2018-10-08 18:58
I have same error:
```
Collecting uvloop
  Using cached https://files.pythonhosted.org/packages/5c/37/6daa39aac42b2deda6ee77f408bec0419b600e27b89b374b0d440af32b10/uvloop-0.11.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\sageev\AppData\Local\Temp\pip-install-bq64l8jy\uvloop\setup.py", line 15, in <module>
        raise RuntimeError('uvloop does not support Windows at the moment')
    RuntimeError: uvloop does not support Windows at the moment
```

**Comment by phoenixjun** [comment] 2019-02-15 05:58
is this supported or not? you can comment if it is not supported so that people like me can stop trying.

**Comment by fkuhn** [comment] 2019-02-22 09:03
I ran into the same issue when trying to install datasette on windows after successfully using it on linux. Unfortunately, there has not been any progress in implementing uvloop for windows - so I recommend not to use it on win. You can read about this issue here:
[https://github.com/MagicStack/uvloop/issues/14](url)

**Comment by simonw** [comment] 2019-02-26 02:14
I'm working on a port of Datasette to Starlette which I think would fix this issue: https://github.com/encode/starlette

**Comment by carsonyl** [comment] 2019-05-04 18:36
Hi @simonw - I just hit this issue when trying out Datasette after your PyCon talk today. Datasette is pinned to Sanic 0.7.0, but it looks like 0.8.0 added the option to remove the uvloop dependency for Windows by having an environment variable `SANIC_NO_UVLOOP` at install time. Maybe that'll be sufficient before a port to Starlette?

**Comment by Maltazar** [comment] 2019-05-07 11:24
I totally agree with carsonyl

**Comment by simonw** [comment] 2019-06-15 21:44
I'm closing his as a duplicate of the new #511 - I hope to have his working very shortly as a result of #272

**Closed by simonw** 2019-06-15 21:44 UTC
