### ISSUE TITLE
base_url is omitted in JSON and CSV views

### ISSUE THREAD

**Issue by phubbard** [simonw/datasette#1519] opened 2021-11-19 18:10 UTC
I have a datasette deployment, using Apache2 to reverse proxy:

       ProxyPass /ged http://thor.phfactor.net:8001
       ProxyPreserveHost On

In settings.json I have
```json
{
    "base_url": "/ged/",
    "trace_debug": 1,
    "template_debug": 1
}
```
and datasette works correctly. However, if you view a query and then click on the 'This data as json, CSV' both links omit the base_url prefix and are therefore 404.

**Comment by simonw** [comment] 2021-11-19 18:31
`base_url` has been a source of so many bugs like this! I often find them quite hard to replicate, likely because I haven't made myself a good Apache `mod_proxy` testing environment yet.

**Comment by simonw** [comment] 2021-11-19 18:32
Having a live demo running on Cloud Run that proxies through Apache and uses `base_url` would be incredibly useful for replicating and debugging this kind of thing. I wonder how hard it is to run Apache and `mod_proxy` in the same Docker container as Datasette?

**Comment by simonw** [comment] 2021-11-19 18:34
This pattern looks like it can help: https://ahmet.im/blog/cloud-run-multiple-processes-easy-way/

**Comment by simonw** [comment] 2021-11-19 20:01
I now have a `Dockerfile` in https://github.com/simonw/datasette/issues/1521#issuecomment-974388295 that I can use to run a local Apache 2 with `mod_proxy` to investigate this class of bugs!

**Comment by simonw** [comment] 2021-11-19 20:02
Bug confirmed:

![proxy-bug](https://user-images.githubusercontent.com/9599/142684666-112136bf-9243-4b6e-8202-339fcfe91bcc.gif)

**Comment by simonw** [comment] 2021-11-19 20:08
The relevant test is this one: https://github.com/simonw/datasette/blob/30255055150d7bc0affc8156adc18295495020ff/tests/test_html.py#L1608-L1649

I modified that test to add `"/fixtures/facetable?sql=select+1"` as one of the tested paths, and dropped in an `assert False` to pause it in the debugger:
```
    @pytest.mark.parametrize(
        "path",
        [
            "/",
            "/fixtures",
            "/fixtures/compound_three_primary_keys",
            "/fixtures/compound_three_primary_keys/a,a,a",
            "/fixtures/paginated_view",
            "/fixtures/facetable",
            "/fixtures/facetable?sql=select+1",
        ],
    )
    def test_base_url_config(app_client_base_url_prefix, path):
        client = app_client_base_url_prefix
        response = client.get("/prefix/" + path.lstrip("/"))
        soup = Soup(response.body, "html.parser")
        if path == "/fixtures/facetable?sql=select+1":
>           assert False
E           assert False
```
BUT... in the debugger:
```
(Pdb) print(soup)
...
<p class="export-links">This data as
  <a href="/prefix/fixtures/facetable.json?sql=select+1&amp;_labels=on">json</a>,
  <a href="/prefix/fixtures/facetable.testall?sql=select+1&amp;_labels=on">testall</a>,
  <a href="/prefix/fixtures/facetable.testnone?sql=select+1&amp;_labels=on">testnone</a>,
  <a href="/prefix/fixtures/facetable.testresponse?sql=select+1&amp;_labels=on">testresponse</a></p>
```
Those all have the correct prefix! But that's not what I'm seeing in my `Dockerfile` reproduction of the issue.

Something very weird is going on here.

**Comment by simonw** [comment] 2021-11-19 20:14
I added `template_debug` in the Dockerfile:
```
datasette fixtures.db --setting template_debug 1 --setting base_url "/foo/bar/" -p 9000 &\n\
```
And then hit `http://localhost:5000/foo/bar/fixtures?sql=select+*+from+compound_three_primary_keys+limit+1&_context=1` to view the template context - and it showed the bug, output edited to just show relevant keys:

```json
{
    "edit_sql_url": "/foo/bar/fixtures?sql=select+%2A+from+compound_three_primary_keys+limit+1",
    "settings": {
        "force_https_urls": false,
        "template_debug": true,
        "trace_debug": false,
        "base_url": "/foo/bar/"
    },
    "show_hide_link": "/fixtures?sql=select+%2A+from+compound_three_primary_keys+limit+1&_context=1&_hide_sql=1",
    "show_hide_text": "hide",
    "show_hide_hidden": "",
    "renderers": {
        "json": "/fixtures.json?sql=select+*+from+compound_three_primary_keys+limit+1&_context=1"
    },
    "url_csv": "/fixtures.csv?sql=select+*+from+compound_three_primary_keys+limit+1&_context=1&_size=max",
    "url_csv_path": "/fixtures.csv",
    "base_url": "/foo/bar/"
}
```
This is so strange. `edit_sql_url` and `base_url` are correct, but `show_hide_link` and `url_csv` and `renderers.json` are not.

**Comment by simonw** [comment] 2021-11-19 20:24
Here's the code that generates `edit_sql_url` correctly: https://github.com/simonw/datasette/blob/85849935292e500ab7a99f8fe0f9546e903baad3/datasette/views/database.py#L416-L420

And  here's the code for `show_hide_link`: https://github.com/simonw/datasette/blob/85849935292e500ab7a99f8fe0f9546e903baad3/datasette/views/database.py#L432-L433

And for `url_csv`: https://github.com/simonw/datasette/blob/85849935292e500ab7a99f8fe0f9546e903baad3/datasette/views/base.py#L600-L602

**Comment by simonw** [comment] 2021-11-19 20:25
The implementations of `path_with_removed_args` and `path_with_format`:

https://github.com/simonw/datasette/blob/85849935292e500ab7a99f8fe0f9546e903baad3/datasette/utils/__init__.py#L228-L254

https://github.com/simonw/datasette/blob/85849935292e500ab7a99f8fe0f9546e903baad3/datasette/utils/__init__.py#L710-L729

**Comment by simonw** [comment] 2021-11-19 20:26
In the `?_context=` debug view the request looks like this:
```
    "request": "<datasette.utils.asgi.Request object at 0x7faf9fe06200>",
```
I'm going to add a `repr()` to it such that it's a bit more useful.

**Comment by simonw** [comment] 2021-11-19 20:31
Modified my `Dockerfile` to do this:

    RUN pip install https://github.com/simonw/datasette/archive/ff0dd4da38d48c2fa9250ecf336002c9ed724e36.zip

And now the `request` in that debug `?_context=1` looks like this:
```
    "request": "<asgi.Request method=\"GET\" url=\"http://localhost:9000/fixtures?sql=select+*+from+compound_three_primary_keys+limit+1&_context=1\">"
```
That explains the bug - that request doesn't maintain the original path prefix of `http://localhost:5000/foo/bar/fixtures?sql=` (also it's been rewritten to `localhost:9000` instead of `localhost:5000`).

**Comment by simonw** [comment] 2021-11-19 20:32
Still not clear why the tests pass but the live example fails.

**Comment by simonw** [comment] 2021-11-19 20:40
Figured it out! The test is not an accurate recreation of what is happening, because it doesn't simulate a request with a path of `/fixtures` that has been redirected by the proxy to `/prefix/fixtures`.

**Comment by simonw** [comment] 2021-11-19 20:41
https://docs.datasette.io/en/stable/deploying.html#apache-proxy-configuration says I should use `ProxyPreserveHost`.

**Comment by simonw** [comment] 2021-11-19 21:15
I think what's happening here is Apache is actually making a request to `/fixtures` rather than making a request to `/prefix/fixtures` - and Datasette is replying to requests on both the prefixed and the non-prefixed paths.

This is pretty confusing! I think Datasette should ONLY reply to `/prefix/fixtures` instead and return a 404 for `/fixtures` - this would make things a whole lot easier to debug.

But shipping that change could break existing deployments. Maybe that should be a breaking change for 1.0.

**Comment by simonw** [comment] 2021-11-19 21:16
In the meantime I can catch these errors by changing the test to run each path twice, once with and once without the prefix. This should accurately simulate how Apache is working here.

**Comment by simonw** [comment] 2021-11-20 00:37
Thanks to #1522 I have a live demo that exhibits this bug now: https://apache-proxy-demo.datasette.io/prefix/fixtures/attraction_characteristic

**Comment by simonw** [comment] 2021-11-20 00:42
> In the meantime I can catch these errors by changing the test to run each path twice, once with and once without the prefix. This should accurately simulate how Apache is working here.

This worked, I managed to get the tests to fail! Here's the change I made:

```diff
diff --git a/tests/test_html.py b/tests/test_html.py
index f24165b..dbdfe59 100644
--- a/tests/test_html.py
+++ b/tests/test_html.py
@@ -1614,12 +1614,19 @@ def test_metadata_sort_desc(app_client):
         "/fixtures/compound_three_primary_keys/a,a,a",
         "/fixtures/paginated_view",
         "/fixtures/facetable",
+        "/fixtures?sql=select+1",
     ],
 )
-def test_base_url_config(app_client_base_url_prefix, path):
+@pytest.mark.parametrize("use_prefix", (True, False))
+def test_base_url_config(app_client_base_url_prefix, path, use_prefix):
     client = app_client_base_url_prefix
-    response = client.get("/prefix/" + path.lstrip("/"))
+    path_to_get = path
+    if use_prefix:
+        path_to_get = "/prefix/" + path.lstrip("/")
+    response = client.get(path_to_get)
     soup = Soup(response.body, "html.parser")
+    if path == "/fixtures?sql=select+1":
+        assert False
     for el in soup.findAll(["a", "link", "script"]):
         if "href" in el.attrs:
             href = el["href"]
@@ -1642,11 +1649,12 @@ def test_base_url_config(app_client_base_url_prefix, path):
             # If this has been made absolute it may start http://localhost/
             if href.startswith("http://localhost/"):
                 href = href[len("http://localost/") :]
-            assert href.startswith("/prefix/"), {
+            assert href.startswith("/prefix/"), json.dumps({
                 "path": path,
+                "path_to_get":  path_to_get,
                 "href_or_src": href,
                 "element_parent": str(el.parent),
-            }
+            }, indent=4, default=repr)
 
 
 def test_base_url_affects_metadata_extra_css_urls(app_client_base_url_prefix):
```

**Comment by simonw** [comment] 2021-11-20 00:53
Adding that test found (I hope!) all of the remaining `base_url` bugs. There were a bunch! I think I finally get to close #838 too.

**Comment by simonw** [comment] 2021-11-20 00:59
Ouch a nasty bug crept through there - https://datasette-apache-proxy-demo-j7hipcg4aq-uc.a.run.app/prefix/fixtures/compound_three_primary_keys says

> 500: name 'ds' is not defined

**Comment by simonw** [comment] 2021-11-20 19:11
OK, i think I got all of them this time!

The latest demo is now live at https://datasette-apache-proxy-demo.fly.dev/prefix/fixtures/sortable?_facet=pk2

I'm closing this issue, but feel free to re-open it if you spot any that I missed.

**Closed by simonw** 2021-11-20 19:11 UTC
Labels: bug

**Comment by simonw** [comment] 2021-11-20 19:42
> I think what's happening here is Apache is actually making a request to `/fixtures` rather than making a request to `/prefix/fixtures` - and Datasette is replying to requests on both the prefixed and the non-prefixed paths.
> 
> This is pretty confusing! I think Datasette should ONLY reply to `/prefix/fixtures` instead and return a 404 for `/fixtures` - this would make things a whole lot easier to debug.
> 
> But shipping that change could break existing deployments. Maybe that should be a breaking change for 1.0.

On further thought I'm not going to do this. Having Datasette work behind a proxy the way it does right now is clearly easy for people to deploy (now that I've fixed the bugs) and I trust my improved tests to catch problems in the future.

**Comment by phubbard** [comment] 2021-12-01 17:50
thanks so very much for the prompt attention and fix! Plus, the animated GIF showing the bug is just extra and I love it. Interactions like this are why I love open source.
