### ISSUE TITLE
Ability to add extra routes and related templates

### ISSUE THREAD

**Issue by clausjuhl** [simonw/datasette#486] opened 2019-05-24 14:04 UTC
Hi Simon

Thank for an excellent job! Datasette is such an obviously good idea (once you have that idea!) and so well done. The only thing that I miss, is the ability to add extras routes (with associated jinja2-templates). For most of the datasets, that I would like to publish, I would also like at least a page, that describes the data (semantics, provenance, biases...) and a page explaining our cookie- and privacy-policies (which would allows us to use something like Goggle Analytics).

**Comment by simonw** [comment] 2019-05-24 14:41
I'm really keen to offer this as a plugin hook once I have Datasette working on ASGI - #272 

I'll hopefully have that working in the next few weeks, but in the meantime there are a couple of tricks you can use:

- you can add static HTML files (no templates though) using the static route configuration options
- you can link to external hosted pages using the `about_url` metadata option
- you can add information to an existing page with a custom template. I do that here for example: https://russian-ira-facebook-ads.datasettes.com/

**Comment by simonw** [comment] 2019-05-24 14:43
Closing this as a dupe of #215

**Closed by simonw** 2019-05-24 14:43 UTC
