### ISSUE TITLE
Allow facetting on custom queries

### ISSUE THREAD

**Issue by Kabouik** [simonw/datasette#1240] opened 2021-02-23 15:52 UTC
Facets are a tremendously useful feature, especially for people peeking at the database for the first time and still having little knowledge about the details of the data. It is of great assistance to discover interesting features to explore futher in advanced queries.

Yet, it seems it's impossible to use facets when running a custom SQL query, be it from the little gear icons in column names, the facet suggestions at the top (hidden when performing a custom query), or by appending a facet code to the URL. 

Is there a technical limitation, or is this something that could be unlocked easily?

**Comment by Kabouik** [comment] 2021-02-23 16:07
Likewise, while answering to another issue regarding the Vega plugin, I realized that there is no such way of linking rows after a custom queries, I only get this "Link" column with individual URLs for the default SQL view:

![ss-2021-02-23_170559](https://user-images.githubusercontent.com/7107523/108871491-1e3fd500-75f1-11eb-8f76-5d5a82cc14d7.png)

Or is it there and I just miss the option in my custom queries?

**Comment by simonw** [comment] 2021-02-26 18:18
Agreed, this would be extremely useful. I'd love to be able to facet against custom queries. It's a fair bit of work to implement but it's not impossible. Closing this as a duplicate of #972.

**Closed by simonw** 2021-02-26 18:18 UTC

**Comment by simonw** [comment] 2021-02-26 18:19
Linking to rows from custom queries is a lot harder - because given an arbitrary string of SQL it's difficult to analyze it and figure out which (if any) of the returned columns represent a primary key.

It's possible to manually write a SQL query that returns a column that will be treated as a link to another page using this plugin, but it's not particularly straight-forward: https://datasette.io/plugins/datasette-json-html
